name: Reusable Tests

on:
  workflow_call:
    secrets:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
        required: true
      CLERK_SECRET_KEY:
        required: true

jobs:
  Reusable-Tests:
    runs-on: ubuntu-latest
    environment: Preview
    env:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
      CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
      DATABASE_URL: postgresql://yourusername:yourpassword@localhost:5432/yourdatabase
      DIRECT_URL: postgresql://yourusername:yourpassword@localhost:5432/yourdatabase
      CLERK_WEBHOOK_SECRET: mock-clerk-webhook-secret
      STRIPE_SECRET_KEY: mock-stripe-secret-key
      AWS_REGION: mock-aws-region
      AWS_ACCESS_KEY_ID: mock-aws-access-key-id
      AWS_SECRET_ACCESS_KEY: mock-aws-secret-access-key
      AWS_PRIVATE_BUCKET_ARN: mock-aws-private-bucket-arn
      AWS_PRIVATE_BUCKET_NAME: noos-private-assets
      AWS_PUBLIC_BUCKET_ARN: mock-aws-public-bucket-arn
      AWS_PUBLIC_BUCKET_NAME: noos-public-assets
      AWS_PUBLIC_BUCKET_URL: mock-aws-public-bucket-url
      STRIPE_WEBHOOK_SECRET: mock-stripe-webhook-secret
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in"
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up"
      NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: "/country"
      NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: "/dashboard/general"
      FORCE_COLOR: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Tests
        run: npm test

      - name: Stop Docker Compose Services
        if: always()
        run: docker compose down
